name: Hello World Workflow

on:
  push:
    branches:
      - main

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "shamshad ansari"
      - name: print here
        run: echo "how are you..??"
